name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  Check-Code:
    runs-on: ubuntu-latest
    steps:
      - name: Environment setup
        run: |
          sudo apt-get update
          sudo apt-get install python3.8 python3.8-venv -y
          git clone https://github.com/sam-don/sentalysis.git
          python3.8 -m venv sentalysis/venv
          sentalysis/venv/bin/pip3 install flake8 mypy
          
      - name: Flake8 Test
        run: |
          sentalysis/venv/bin/flake8 sentalysis/main.py
          sentalysis/venv/bin/flake8 sentalysis/Analysis.py
          sentalysis/venv/bin/flake8 sentalysis/Twitter.py

      - name: Mypy Test
        run: |
          sentalysis/venv/bin/mypy sentalysis/main.py
          sentalysis/venv/bin/mypy sentalysis/Twitter.py
          sentalysis/venv/bin/mypy sentalysis/Analysis.py
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Environment setup
        run: |
          sudo apt-get update
          sudo apt-get install python3.8 python3.8-venv -y
          git clone https://github.com/sam-don/sentalysis.git
          cd sentalysis
          python3.8 -m venv venv
          venv/bin/pip3 install -r requirements.txt

      - name: Run Tests
        run: |
          cd sentalysis
          venv/bin/python3.8 -m unittest discover tests/
  Deployment:
    needs: [Check-Code, Run-Tests]
    runs-on: ubuntu-latest
    steps:
      - name: Fresh clone & repo install
        uses: appleboy/ssh-action@master
        with:
          host: 3.211.122.190
          username: github-actions
          key: ${{ secrests.ssh_key }}
          port: 22
          script: |
            rm -rf sentalysis
            git clone https://github.com/sam-don/sentalysis.git
            python3.8 -m venv /home/github-actions/sentalysis/venv
            /home/github-actions/sentalysis/venv/bin/pip3.8 install -r /home/github-actions/sentalysis/requirements.txt