name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  Check-Code:
    runs-on: ubuntu-latest
    steps:
      - name: Environment setup
        run: |
          sudo apt-get update
          sudo apt-get install python3.8 python3.8-venv -y
          git clone https://github.com/sam-don/sentalysis.git
          python3.8 -m venv sentalysis/venv
          
      - name: Flake8 Test
        run: |
          sentalysis/venv/bin/pip3 install flake8
          sentalysis/venv/bin/flake8 sentalysis/main.py