name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  Check-Code:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install python3.8 python3.8-venv -y
          git clone https://github.com/sam-don/sentalysis.git
          python3.8 -m venv sentalysis/venv
          sentalysis/venv/bin/pip3 install flake8
          sentalysis/venv/bin/flake8 sentalysis/main.py